# Generated by Django 5.2.6 on 2025-10-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('street_number', models.CharField(max_length=10)),
                ('street_name', models.CharField(max_length=100)),
                ('apartment', models.CharField(blank=True, max_length=20, null=True)),
                ('zipcode', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('registration_date', models.DateField()),
                ('party', models.CharField(max_length=2)),
                ('precinct', models.CharField(max_length=5)),
                ('v20state', models.BooleanField(default=False)),
                ('v21town', models.BooleanField(default=False)),
                ('v21primary', models.BooleanField(default=False)),
                ('v22general', models.BooleanField(default=False)),
                ('v23town', models.BooleanField(default=False)),
                ('voter_score', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
