# Generated by Codex CLI: Add user FK to Profile
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0004_comment_follow_like'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(
                related_name='profiles',
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='auth.user'
            ),
        ),
    ]

