# Generated by Codex CLI: Backfill Profile.user to default admin/first user
from django.db import migrations


def attach_default_user(apps, schema_editor):
    Profile = apps.get_model('mini_insta', 'Profile')
    User = apps.get_model('auth', 'User')

    # Prefer a superuser; otherwise first available user
    default_user = User.objects.filter(is_superuser=True).order_by('id').first() or User.objects.order_by('id').first()
    if not default_user:
        # No user exists yet; nothing to backfill
        return
    Profile.objects.filter(user__isnull=True).update(user=default_user)


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0005_profile_user'),
    ]

    operations = [
        migrations.RunPython(attach_default_user, reverse_code=migrations.RunPython.noop),
    ]

