# Generated by Django 4.2.20 on 2025-11-24 22:48

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(help_text='Card number within the set', max_length=20)),
                ('rarity', models.CharField(choices=[('COMMON', 'Common'), ('UNCOMMON', 'Uncommon'), ('RARE', 'Rare'), ('ULTRA_RARE', 'Ultra Rare'), ('LEGENDARY', 'Legendary'), ('ROOKIE', 'Rookie Card'), ('AUTOGRAPH', 'Autograph'), ('PATCH', 'Patch Card'), ('SERIAL', 'Serial Numbered'), ('PRIZM', 'Prizm')], max_length=20)),
                ('serial_number', models.CharField(blank=True, help_text='Serial number if numbered card', max_length=50, null=True)),
                ('image', models.URLField(blank=True, help_text='URL to card image', null=True)),
                ('estimated_value', models.DecimalField(decimal_places=2, help_text='Estimated market value in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['set__release_year', 'set__name', 'card_number'],
            },
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(choices=[('PANINI', 'Panini'), ('TOPPS', 'Topps'), ('UPPER_DECK', 'Upper Deck'), ('LEAF', 'Leaf Trading Cards'), ('FUTERA', 'Futera'), ('OTHER', 'Other')], max_length=100)),
                ('release_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2025)])),
                ('sport', models.CharField(default='Soccer', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_cards', models.PositiveIntegerField(blank=True, help_text='Total number of cards in set', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-release_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('CB', 'Center Back'), ('LB', 'Left Back'), ('RB', 'Right Back'), ('CM', 'Central Midfielder'), ('LM', 'Left Midfielder'), ('RM', 'Right Midfielder'), ('CAM', 'Central Attacking Midfielder'), ('LW', 'Left Winger'), ('RW', 'Right Winger'), ('ST', 'Striker'), ('CF', 'Center Forward')], max_length=50)),
                ('club_team', models.CharField(max_length=100)),
                ('birth_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2010)])),
                ('image', models.URLField(blank=True, help_text='URL to player image', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Price paid for this card', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('purchase_date', models.DateField()),
                ('grade', models.CharField(choices=[('UNGRADED', 'Ungraded'), ('PSA', 'PSA'), ('BGS', 'Beckett'), ('SGC', 'SGC'), ('CGC', 'CGC')], default='UNGRADED', max_length=20)),
                ('grade_score', models.PositiveIntegerField(blank=True, help_text='Numerical grade if professionally graded', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('condition_note', models.TextField(blank=True, help_text='Additional condition notes', null=True)),
                ('for_sale', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Asking price if for sale', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_by', to='project.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='project.player'),
        ),
        migrations.AddField(
            model_name='card',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='project.cardset'),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('set', 'card_number')},
        ),
    ]
