# Generated by Django 6.0 on 2025-12-08 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('favorite_cards', models.ManyToManyField(blank=True, related_name='favored_by', to='project.card')),
                ('friends', models.ManyToManyField(blank=True, related_name='friends_with', to='project.profile')),
                ('trade_list', models.ManyToManyField(blank=True, related_name='trade_listed_by', to='project.card')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ManyToManyField(blank=True, related_name='wishlisted_by', to='project.card')),
            ],
        ),
    ]
